name: Sub-job-Test-Unit

on:
  workflow_call:

jobs:
  test-unit:
    name: Maven Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Unit Test
        run: mvn test --file pom.xml
  test-ut-coverage:
    name: Jacoco Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Jacoco
        run: mvn jacoco:report --file pom.xml