name: Maven

on:
  workflow_call:

jobs:
  check-compile:
    name: Maven Compile Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile with Maven
        run: mvn compile --file pom.xml
  check-codestyle:
    name: Check Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile with Maven
        run: mvn checkstyle:check --file pom.xml