name: Lib Maven Pipeline

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: ['*']

jobs:
  check:
    name: Pre-check Codes
    uses: ./.github/workflows/callable.check.yml
  test-ut:
    name: Unit Test
    uses: ./.github/workflows/callable.test.ut.yml
    needs: check
  sast-normal:
    name: SAST Code Analysis (Normal)
    uses: ./.github/workflows/callable.test.sast.normal.yml
    needs: test-ut
    permissions:
      actions: read
      contents: read
      security-events: write
  sast-advanced:
    name: SAST Code Analysis (Advanced)
    uses: ./.github/workflows/callable.test.sast.advanced.yml
    needs: test-ut
    secrets: inherit
    permissions:
      actions: read
      contents: read
      security-events: write