name: Lib Maven Pipeline

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: ['*']

jobs:
  check:
    name: Pre-check Codes
    uses: ./.github/workflows/callable.check.yml